### ISSUE TITLE
MakeCommand::handle() does not exist

### ISSUE THREAD

**Issue by robcaa** [Niellles/lumen-commands#3]
```php artisan make:controller ...```
Method Niellles\LumenCommands\Commands\ControllerMakeCommand::handle() does not exist.

Same issue when make modell or another.

Version:
"laravel/lumen-framework": "5.5.*",

**Comment by monder007** [comment]
Add

`public function handle() { return $this->fire(); }`

into the GeneratorCommand.php

**Comment by robcaa** [comment]
Thanks, this temporary solution works.
But the vendor folder is not recommended to edit.

**Comment by Niellles** [comment]
I'll look into this when I get the the time, Not currently working with Lumen (or this package for that matter) though. Feel free to do a pull request.

**Comment by Niellles** [comment]
Finally checked this out -- kinda forgot about it. I've merged a pull request, that replaces `fire()` with `handle()`. I've tested it, although not extensively, and as far as I can tell this fixes this issue. The package also still works with older versions of Lumen.
