### ISSUE TITLE
Class 'Niellles\LumenCommands\RuntimeException' not found

### ISSUE THREAD

**Issue by semsphy** [Niellles/lumen-commands#6]
In GeneratorCommand.php line 206:
`Class 'Niellles\LumenCommands\RuntimeException' not found`

**Comment by Niellles** [comment]
I'll commit a fix when I get the time, probably tomorrow.

However, the error that you're getting is only saying that it can't find the error that it's trying to throw. It's trying to tell you that it's 'Unable to detect application namespace'. Could you provide some more context for your error? For example, which version of Lumen are you running?
