### ISSUE TITLE
Class 'Niellles\LumenCommands\LumenCommandsServiceProvider' not found  

### ISSUE THREAD

**Issue by Kaushikk369** [Niellles/lumen-commands#9]
I tried 
php artisan make:middleware name it gives such error.

**Comment by Niellles** [comment]
- What version of Lumen are you running?
- Did you successfully install with `composer install`?
- What is your APP_ENV set to in .env?
- Did you bind the Serviceprovider in app.php like so:
```
if (env('APP_ENV') === 'local') {
    $app->bind(Illuminate\Database\ConnectionResolverInterface::class, Illuminate\Database\ConnectionResolver::class);
    $app->register(Niellles\LumenCommands\LumenCommandsServiceProvider::class);
}
```

**Comment by Kaushikk369** [comment]
@Niellles thanks

**Comment by Niellles** [comment]
@Kaushiksshinde Did one of my comments resolve your issue?
